<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Timezone</name>
   <tag></tag>
   <elementGuidId>cc2a503d-1b26-4633-8d88-abd403ee307e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.ui-float-right</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.ui-float-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Inline Frames/AutoAlert iFrame</value>
   </webElementProperties>
</WebElementEntity>
