<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lease</name>
   <tag></tag>
   <elementGuidId>5a00706f-9d77-4300-b5f2-8a3b1559721b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SalesType_lease</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SalesType_lease</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Inline Frames/AutoAlert iFrame</value>
   </webElementProperties>
</WebElementEntity>
