<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>New</name>
   <tag></tag>
   <elementGuidId>84fb4abe-526e-4ebb-835f-a6b1369de2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#VehicleType_New</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#VehicleType_New</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Inline Frames/AutoAlert iFrame</value>
   </webElementProperties>
</WebElementEntity>
