<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Retail</name>
   <tag></tag>
   <elementGuidId>17724ec5-78f1-47e5-a1de-71f691978336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SalesType_retail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SalesType_retail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Inline Frames/AutoAlert iFrame</value>
   </webElementProperties>
</WebElementEntity>
