<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Used</name>
   <tag></tag>
   <elementGuidId>9a81bea0-b85b-47ea-b398-d3bd9a3ba925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#VehicleType_Used</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#VehicleType_Used</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Inline Frames/AutoAlert iFrame</value>
   </webElementProperties>
</WebElementEntity>
